<a href="https://colab.research.google.com/github/javialra97/IQ/blob/main/cp_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase Práctica #7 de Informática Química
Autor: [Javier Emilio Alfonso Ramos](https://scholar.google.com/citations?user=AcJIzk4AAAAJ&hl=es)  (javialra97@gmail.com)

Es esta clase práctica trabajaremos directamente en la nube, haciendo uso de las facilidades ofrecidas por Google a través de **Google Colaboratory**.

El objetivo es que a través del lenguaje de programación Python obtendramos algunas propiedades químicas como pueden ser las cargas parciales, momento dipolo y geometría de la molecula de agua.

Para esto necesitamos una biblioteca que permita realizar este tipo de operaciones. Para eso usaremos el programa PySCF<sup>[1,2,3]</sup>. Este programa esta escrito totalmente en Python de manera que uno pueda importar las bibliotecas y funciones que necesite. Para más información puede tocar [aquí](https://pyscf.org/).

Como es de esperar estas funciones no forman parte de las bibliotecas estándar de Python por lo que lo primero que hace falta es instalar. En Python hay varias maneras de instalar este tipo de módulos, no ahondaremos en eso, sencillamente escogeremos uno de ellos, [pip](https://pypi.org/project/pip/). 


In [1]:
! pip install pyscf
! pip install pyberny
! pip install mogli

     |████████████████████████████████| 37.5 MB 1.4 MB/s 
     |████████████████████████████████| 206 kB 31.7 MB/s 
     |████████████████████████████████| 126 kB 33.9 MB/s 
  Created wheel for mogli: filename=mogli-0.3.0-py3-none-any.whl size=10630 sha256=11e13f445adb1bacf67b8a2c22e6e60c17e895f5bfca50e1598e2be5132a11cb
  Stored in directory: /root/.cache/pip/wheels/75/01/df/15165d257d23a3e9035460c59c96113f4be08241a7ec138615
  Created wheel for gr: filename=gr-1.20.0-cp37-cp37m-linux_x86_64.whl size=20939797 sha256=5e1af305017083a7fe57e4b15c26a3981cb5e325a18543e96bf3c73a164e56d7
  Stored in directory: /root/.cache/pip/wheels/4c/f7/82/033951f4018677d5fd6ee622fa683793f52fd0d58636ba0dad
Successfully built mogli gr


Las dos primeras líneas instalan el programa PySCF. Mogli nos permitira visualizar la molécula de agua desde el mismo navegador. Hay muchos programas que permiten esto (GaussView, Avogadro, ChemCraft ...) pero el sentido es hacerlo todo con códigos de Python. La informacion de Mogli la pueden encontrar en su [repositorio de GitHub](https://github.com/sciapp/mogli).

Una vez que estén instalados las bibliotecas necesarias, cual sería el próximo paso🤔? ... Tendremos que importar aquellas funciones que nos permitirán realizar el cálculos de las propiedades de interés.

In [2]:
from pyscf import gto, scf
from pyscf.geomopt.berny_solver import optimize

La primera línea esta importando aquellas funciones que nos permitirán resolver de manera aproximada una de las más famosas ecuaciones de la mecánica cuántica, la ecuación de Schröndinger(no relativista independiente del tiempo):

$ \hat{H}Ψ = EΨ $

Como nuestro interés es encontrar la geometría de equilibrio, tendremos que buscar una función que optimice la estructura inicial que le daremos como entrada. Extrapolando un poco los conocimientos adquiridos en Análisis Matemático I, lo que estamos buscando es el conjunto óptimos de parámetros que describan a la molécula de agua, estos serían la distancia de enlace O-H y el ángulo de enlace HOH.

La entrada de nuestro programa queda claro que es la molécula de agua pero hasta el momento no la hemos definido. Necesitamos escribirla de una manera que nuestro programa entienda que es la molécula de agua (un poco abstracto ehh..). Hay varias maneras de hacer esto, nosotros escogeremos la representación cartesiana. Tendriamos que declarar las coordenadas xyz de tres puntos en el espacio. 

In [3]:
mol_agua = gto.M (atom = ''' O 0 0 0; H 0 1 0; H 0 0 1 ''', basis = 'sto-3g',)

En la primera linea declaramos a nuestra molécula de agua. Fijense que el átomo de oxígeno se encuentra en el centro del eje de coordenadas mientras que los átomos de hidrógeno se encuentran desplazados una unidad en el eje de las *y* y en el eje de las *z*. 

Ahora vamos a buscar el mínimo(optimizar) y mostrar las coordenas de esta nueva geometría.

In [4]:
mol_eq = optimize(mol_agua)
print("\n")
print(mol_eq.atom_coords())

converged SCF energy = -74.9611711378677
converged SCF energy = -74.9611711378677
converged SCF energy = -74.9611711378677

Geometry optimization cycle 1
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O   0.000000   0.000000   0.000000    0.000000  0.000000  0.000000
   H   0.000000   1.000000   0.000000    0.000000  0.000000  0.000000
   H   0.000000   0.000000   1.000000    0.000000  0.000000  0.000000
converged SCF energy = -74.9611711378677
--------------- SCF_Scanner gradients ---------------
         x                y                z
0 O    -0.0000000000    -0.0334678269    -0.0334678269
1 H     0.0000000000     0.0048875662     0.0285802607
2 H     0.0000000000     0.0285802607     0.0048875662
----------------------------------------------
cycle 1: E = -74.9611711379  dE = -74.9612  norm(grad) = 0.0626229

Geometry optimization cycle 2
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY   

Como la solución de este sistema es por vía numérica, verán que aparecen diferentes iteraciones y al final podemos ver como los átomos se desplazaron de sus posiciones iniciales. Un pequeño calculo de distancia euclidiana nos muestra como las distancias son diferentes de la unidad.



In [5]:
import numpy as np
coord_O = np.array([mol_eq.atom_coords()[0][0], mol_eq.atom_coords()[0][1], mol_eq.atom_coords()[0][2]])
coord_H = np.array([mol_eq.atom_coords()[1][0], mol_eq.atom_coords()[1][1], mol_eq.atom_coords()[1][2]])
dist_OH = np.linalg.norm(coord_O - coord_H)
print(dist_OH)

1.869697315105809


La distancia anterior esta en Bohr, que es aproximadamente 1 A, la cual es la que se reporta para la molécula de agua, recuerden que la molécula inicial tenia una distancia de enlace de 1 Bohr.

Ahora vamos a calcular algunas propiedades de interés a una molécula de agua en fase gaseosa.


In [6]:
mol_eq.verbose = 5
hf_calc = mol_eq.RHF()
hf_calc.kernel()
hf_calc.analyze()



******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-09
SCF conv_tol_grad = None
SCF max_cycles = 50
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /content/tmp6wlvsvvj
max_memory 4000 MB (current use 150 MB)
Set gradient conv threshold to 3.16228e-05
E1 = -119.97135511363322  E_coul = 36.29760269034282
init E= -74.7671858438172
cond(S) = 5.248366697323701
    CPU time for initialize scf      0.08 sec, wall time      0.08 sec
  HOMO = -0.384161165039235  LUMO = 0.400498442939413
  mo_energy =
[-20.57781814  -1.55454571  -0.6721965   -0.53166218  -0.38416117
   0.40049844   0.49101725]
E1 = -123.07863281279633  E_coul = 39.26222823870809
cycle= 1 E= -74.909837994615  delta_E= -0.143  |g|= 0.384  |ddm|= 1.69
    CPU time for cycle= 1      0.02 sec, wall time      0.02 sec
  HOMO = -0.258148061721674  LUMO

((array([1.99990272, 1.71490464, 2.        , 1.26141168, 1.26141168,
         0.88118463, 0.88118463]),
  array([-0.23763074,  0.11881537,  0.11881537])),
 array([-2.09327395e-16,  1.20860753e+00,  1.20860753e+00]))

En estas líneas se esta resolviendo de manera aproximada la ecuación de Schrödinger. La primera línea específica cuan detallada es la salida.

En el principio de la salida podemos ver los paramétros estándar del programa puesto que nosotros no hemos ajustado ninguno, solo que el método sea RHF(*Restricted Hartree-Fock*).

Como les habiamos comentado anteriormente, esta solución se basa en un método iterativo, por eso ven varios ciclos con resultados similares y en cada uno muestra el tiempo de ejecución en CPU. Recuerden que este entorno nos permite hacer uso de GPU y TPU pero en este caso no es necesario reservar ese tipo de recurso.

Una vez que terminen los ciclos nos muestran un resumen con los principales valores energéticos así como las energías y coeficientes de los Orbitales Moleculares (no se asusten, este término lo dominarán a partir del próximo semestre)

En el final se pueden ver las cargas parciales atómicas (de acuerdo al esquema de partición de Mulliken) así como la descomposición del momento dipolo en cada eje.

Una vez terminada esta parte vamos ahora a visualizar esta molécula usando la biblioteca Mogli.

Para esto necesitamos crear un fichero con extensión *.xyz*. 


In [7]:
coor = mol_eq.atom_coords()
label = ['O', 'H', 'H']
print(coor)

with open('agua_eq.xyz', 'w') as file:
  file.write('3\n\n')
  for i,j in zip(label, coor):
    file.write(i + '  ' + str(j[0]) + '  ' + str(j[1]) + '  ' + str(j[2]) + ' \n')

[[ 0.          0.06351417  0.06351417]
 [ 0.          1.92606095 -0.099849  ]
 [ 0.         -0.099849    1.92606095]]


De esta manera ya creamos el fichero de coordenadas de la molecula de agua optimizada en formato *.xyz*. A la izquierda podemos ver un simbolo de una carpeta, den click ahi y veran que ahora hay un fichero que se llama agua_eq.xyz. Den doble click y cuando se les descargue mirenlo con un editor de texto

Una vez que ya tenemos preparado la entrada para las funciones de la biblioteca Mogli vamos a importarlas y generar la visualizacion.

In [8]:
import mogli, gr
molecule = mogli.read('agua_eq.xyz')
mogli.bond_method = 'constant_delta'
mogli.BOND_RADIUS = 0.50
mogli.export(molecule[0], 'agua_eq.html', camera=((40,0,0),(0,0,0),(0,1,0)), bonds_param= 1.95)

## Referencias:

1. [Recent developments in the PySCF program package](https://aip.scitation.org/doi/10.1063/5.0006074), *J. Chem. Phys.* **153**, 024109 (2020)
2. [PySCF: the Python-based simulations of chemistry framework](https://wires.onlinelibrary.wiley.com/doi/10.1002/wcms.1340), *WIREs Comput. Mol. Sci.* **8**, e1340 (2018)
3. [Libcint: An efficient general integral library for Gaussian basis functions](https://onlinelibrary.wiley.com/doi/10.1002/jcc.23981), *J. Comp. Chem.* **36**, 1664 (2015)
